spring:
  application:
    name: p-24-260305

  profiles:
    active: dev

  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  default-produces-media-type: application/json; charset=UTF-8

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: INFO

# 사용자 정의 설정 변수
custom:
  jwt:
    secretPattern: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
    expiration: "#{15 * 60}" # 초 단위
